### ISSUE TITLE
NEI plugin

### ISSUE THREAD

**Issue by ghost** [Skrallexxx/SimpleOres-2#2]
Requesting NEI plugin for the Fusion Furnace.

**Comment by Vexatos** [comment]
:+1:

**Comment by Skrallexxx** [comment]
I have looked into making an NEI plugin for the Fusion Furnace but there doesn't seem to be much documentation on it. It's on the to-do list though, so I will keep looking.

**Comment by ghost** [comment]
This might help: https://github.com/aidancbrady/Mekanism/blob/master/common/mekanism/client/nei/CrusherRecipeHandler.java

**Comment by ghost** [comment]
I am working on this.
