### ISSUE TITLE
Full Localization support

### ISSUE THREAD

**Issue by Vexatos** [Skrallexxx/SimpleOres-2#3]
As mentined before this repo change, I would like this mod to fully support localizations like a lot of other Forge mods do. Then people could play this nice mod in the language they want without modifying any config file. I am sure I am not the only one who wants that.
@crafteverywhere and @VeryBigBro, are you interested? Try this nice mod if you haven't already!

**Comment by labpaw** [comment]
:+1: Maybe I'll work on that.

**Comment by crafteverywhere** [comment]
When it's ready,I will try to work on that.

**Comment by Skrallexxx** [comment]
Found a way to do this, working on it right now. It will be in the next release.

**Comment by Skrallexxx** [comment]
Does anyone have any languages they would like to do? I can send you the english file and then you can translate it from there. I have already done Russian, using the previous Russian translation, however I did have to add a few things, so I just used Google Translate for them.

**Comment by crafteverywhere** [comment]
VeryBigBro can help u with Russian,and I can translate it to Chinese(zh_CN and zh_TW).

**Comment by Skrallexxx** [comment]
Here is the default English translation: https://dl.dropboxusercontent.com/u/66466201/Other/en_US.xml

Go ahead and translate it to whatever language you want. Make sure you change the "en_US.xml" name to whatever is the correct localisation. 

Send me the link once you have finished them and I will add them :)

**Comment by crafteverywhere** [comment]
zh_CN here:http://pastebin.com/WjeNZfXY
zh_TW here:http://pastebin.com/12aLbzwu

**Comment by Vexatos** [comment]
@AleXndrTheGr8st Thank you for implementing it!
@crafteverywhere Nice!

Here is the German file, de_DE.xml: https://dl.dropboxusercontent.com/u/57704711/Dokumente/Speziell/Minecraft/Mods/SimpleOresII/de_DE.xml

@AleXndrTheGr8st Question: Where is the Fusion stuff?

**Comment by Skrallexxx** [comment]
Thanks for that, I'll add it. I'm attempting to implement a way to add more without me directly adding the file path to the code, as well.

**Comment by labpaw** [comment]
Russian Localization here: https://docs.google.com/file/d/0BwHDCyyzhWpiZlVuQ2F3T2dWS28/edit?usp=sharing
Based on Qerter work, some names changed.
