### ISSUE TITLE
Updated de_DE.xml

### ISSUE THREAD

**Issue by Vexatos** [Skrallexxx/SimpleOres-2#7]
I updated the German localization file. Get it here:
https://dl.dropboxusercontent.com/u/57704711/Dokumente/Speziell/Minecraft/Mods/SimpleOresII/1.1.1/de_DE.xml

**Comment by labpaw** [comment]
I've updated Russian localization too. Link: http://goo.gl/s7yHRT
And I've also translated Fusion plugin. Link: http://goo.gl/0hgKnP
@Vexatos Are you interesting in Fusion plugin? If you didn't see it. English file here: http://goo.gl/CS1ReR

**Comment by Vexatos** [comment]
@VeryBigBro Thank you.
Here is my Fusion Plugin lang file:
https://dl.dropboxusercontent.com/u/57704711/Dokumente/Speziell/Minecraft/Mods/SimpleOresII/1.1.1/Fusion/de_DE.xml

**Comment by Skrallexxx** [comment]
Thanks for the updated lang files everyone :) I have added the Fusion ones to the mod, and replaced the old SimpleOres ones with the new ones :) I think I'll close this issue and create a new one just for Localisations though.
