### ISSUE TITLE
Official Localisation Topic

### ISSUE THREAD

**Issue by Skrallexxx** [Skrallexxx/SimpleOres-2#8]
Please leave any updated/new localisation files here and I'll make sure they are added to the mods :)

**Comment by Zot201** [comment]
The Japanese localisation. 
https://github.com/Zot201/SimpleOres-2/blob/master/assets/simpleores/langs/ja_JP.xml

**Comment by Zot201** [comment]
For the fusion plugin as well. 
https://github.com/Zot201/SimpleOres-2/blob/master/assets/simpleoresfusion/langs/ja_JP.xml

**Comment by Skrallexxx** [comment]
Thanks, adding them now.

EDIT: Hmm. I can't get it to switch to this one for some reason. Other languages work fine. Could you please try uploading it to Dropbox or Mediafire or somewhere else please?

Thanks :)

**Comment by Zot201** [comment]
Traditional Chinese localisation
https://github.com/Zot201/SimpleOres-2/blob/master/assets/simpleores/langs/zh_TW.xml

OK I'm going to pack them all into a zip archive when I have them all finished, so please wait a little more.

**Comment by Zot201** [comment]
Traditional Chinese localisation for the fusion plugin
https://github.com/Zot201/SimpleOres-2/blob/master/assets/simpleoresfusion/langs/zh_TW.xml

Simplified Chinese localisation
https://github.com/Zot201/SimpleOres-2/blob/master/assets/simpleores/langs/zh_CN.xml

The last one! Simplified Chinese localisation for the fusion plugin
https://github.com/Zot201/SimpleOres-2/blob/master/assets/simpleoresfusion/langs/zh_CN.xml

A zip archive of all the localisation files above. 
http://www.mediafire.com/download/ljnvbdbttdubxh7/SimpleOres_Localisation_files_(ja_JP%2C_zh_TW_and_zh_CN).zip

**Comment by Vexatos** [comment]
You might want to delete all these messages and put them into a single one. Hint: There is an "Edit" Button in the top left of the comment, next to the "Delete" Button.

**Comment by Zot201** [comment]
Now I've some of them merged. Thanks for your suggestion.

**Comment by Zot201** [comment]
Load all the localisation files automatically.
498bb604605b1a06d4482df456ed1bd48faf8673

**Comment by Skrallexxx** [comment]
Thanks for those zot, adding them right now. I also implemented the code for loading them automatically.

**Comment by Skrallexxx** [comment]
Due to the new method for loading localisations that's built into Forge 1.7.2, I'm closing this. The new lang file style has changed so they will unfortunately have to be re-done. It can mostly be done with some find and replace however.
